Repository six-do-string/jobshin, pull requests merged in 2024-08, with the labels that each got.

#1 feat: 프로젝트 초기 환경 설정
  build.gradle
  src/main/java/com/est/jobshin/interview/controller/InterviewController.java
  src/main/java/com/est/jobshin/interview/domain/Interview.java
  src/main/java/com/est/jobshin/interview/dto/InterviewDto.java
  src/main/java/com/est/jobshin/interview/repository/InterviewRepository.java
  src/main/java/com/est/jobshin/interview/service/InterviewService.java
  src/main/java/com/est/jobshin/user/controller/UserController.java
  src/main/java/com/est/jobshin/user/domain/User.java
  src/main/java/com/est/jobshin/user/dto/UserDto.java
  src/main/java/com/est/jobshin/user/repository/UserRepository.java
  src/main/java/com/est/jobshin/user/service/UserService.java
  src/main/resources/application.yml
Labels: enhancement

#2 Chore: 패키지 구조 변경
  src/main/java/com/est/jobshin/domain/interview/controller/InterviewController.java
  src/main/java/com/est/jobshin/domain/interview/domain/Interview.java
  src/main/java/com/est/jobshin/domain/interview/dto/InterviewDto.java
  src/main/java/com/est/jobshin/domain/interview/repository/InterviewRepository.java
  src/main/java/com/est/jobshin/domain/interview/service/InterviewService.java
  src/main/java/com/est/jobshin/domain/user/controller/UserController.java
  src/main/java/com/est/jobshin/domain/user/domain/User.java
  src/main/java/com/est/jobshin/domain/user/dto/UserDto.java
  src/main/java/com/est/jobshin/domain/user/repository/UserRepository.java
  src/main/java/com/est/jobshin/domain/user/service/UserService.java
  src/main/java/com/est/jobshin/interview/dto/InterviewDto.java
  src/main/java/com/est/jobshin/user/dto/UserDto.java
Labels: documentation

#5 Feat: 로그인 테스팅 기능 구현 완료
  src/main/java/com/est/jobshin/domain/user/controller/UserController.java
Labels: 기능개발

#7 Feat post crud
  src/main/java/com/est/jobshin/domain/posts/controller/PostController.java
  src/main/java/com/est/jobshin/domain/posts/domain/Post.java
  src/main/java/com/est/jobshin/domain/posts/dto/PostDto.java
  src/main/java/com/est/jobshin/domain/posts/repository/PostRepository.java
  src/main/java/com/est/jobshin/domain/posts/service/PostService.java
  src/main/java/com/est/jobshin/global/error/GlobalExceptionHandler.java
Labels: 기능개발

#15 Refactor: 불필요한 ErrorMessage 클래스 삭제
  src/main/java/com/est/jobshin/global/error/ErrorMessage.java
Labels: 리펙토링

#18 feat: Security 인증 로직 작성, User 회원가입 로직 작성(이메일 중복검사 체크 로직 추가 및 리펙토링 필요)
  src/main/java/com/est/jobshin/domain/user/controller/UserController.java
  src/main/java/com/est/jobshin/domain/user/domain/User.java
  src/main/java/com/est/jobshin/domain/user/dto/CreateUserRequest.java
  src/main/java/com/est/jobshin/domain/user/dto/UserResponse.java
  src/main/java/com/est/jobshin/domain/user/repository/UserRepository.java
  src/main/java/com/est/jobshin/domain/user/service/UserService.java
  src/main/java/com/est/jobshin/domain/user/util/BaseEntity.java
  src/main/java/com/est/jobshin/domain/user/util/Language.java
  src/main/java/com/est/jobshin/domain/user/util/Level.java
  src/main/java/com/est/jobshin/domain/user/util/Position.java
  src/main/java/com/est/jobshin/global/security/config/AuthConfig.java
  src/main/java/com/est/jobshin/global/security/config/SecurityConfig.java
  src/main/java/com/est/jobshin/global/security/handler/CustomAuthenticationFailureHandler.java
  src/main/java/com/est/jobshin/global/security/model/CustomUserDetails.java
  src/main/java/com/est/jobshin/global/security/provider/UserAuthenticationProvider.java
  src/main/java/com/est/jobshin/global/security/service/UserDetailService.java
Labels: 기능개발

#19 Feat readpost
  src/main/java/com/est/jobshin/domain/posts/controller/PostController.java
  src/main/java/com/est/jobshin/domain/posts/dto/PostDetailDto.java
  src/main/java/com/est/jobshin/domain/posts/dto/PostSummaryDto.java
  src/main/java/com/est/jobshin/domain/posts/service/PostService.java
  src/main/java/com/est/jobshin/global/error/GlobalExceptionHandler.java
Labels: 기능개발

#21 feat: LevelFeedback html, cssm js 작성
  src/main/resources/static/css/LevelFeedback.css
  src/main/resources/static/js/LevelFeedback.js
  src/main/resources/templates/LevelFeedback.html
Labels: 기능개발

#24 Feat: AiFeedback 프론트 화면 작업
  src/main/resources/static/css/AlFeedback.css
  src/main/resources/static/js/AlFeedback.js
  src/main/resources/templates/AlFeedback.html
Labels: 기능개발

#27 Fix: 충돌로 생긴 컴파일 에러 제거
  build.gradle
  src/main/java/com/est/jobshin/domain/user/domain/User.java
  src/main/java/com/est/jobshin/infra/alan/AlanService.java
Labels: 버그

#29 Feat: levelFeedback 기능 작업
  src/main/java/com/est/jobshin/domain/levelfeedback/controller/LevelFeedbackController.java
  src/main/java/com/est/jobshin/domain/levelfeedback/domain/LevelFeedback.java
  src/main/java/com/est/jobshin/domain/levelfeedback/dto/LevelFeedbackDto.java
  src/main/java/com/est/jobshin/domain/levelfeedback/repository/LevelFeedbackRepository.java
  src/main/java/com/est/jobshin/domain/levelfeedback/service/LevelFeedbackService.java
Labels: 기능개발

#31 feat: 시큐리티 의존성 변경, 회원가입 SSR 방식으로 변경, 로그인 기능 추가
  src/main/java/com/est/jobshin/domain/user/controller/UserController.java
  src/main/java/com/est/jobshin/domain/user/domain/User.java
  src/main/java/com/est/jobshin/domain/user/dto/LoginRequest.java
  src/main/java/com/est/jobshin/domain/user/dto/UserResponse.java
  src/main/java/com/est/jobshin/domain/user/service/UserService.java
  src/main/java/com/est/jobshin/global/security/config/SecurityConfig.java
  src/main/java/com/est/jobshin/global/security/handler/CustomAuthenticationFailureHandler.java
  src/main/java/com/est/jobshin/global/security/model/CustomUserDetails.java
  src/main/java/com/est/jobshin/global/security/provider/UserAuthenticationProvider.java
  src/main/java/com/est/jobshin/global/security/service/UserDetailService.java
Labels: 기능개발

#34 Fix: 실전모드 질문 생성 관련 코드 수정
  src/main/java/com/est/jobshin/domain/interview/dto/InterviewDto.java
  src/main/java/com/est/jobshin/domain/interviewDetail/controller/InterviewDetailController.java
  src/main/java/com/est/jobshin/domain/interviewDetail/domain/InterviewDetail.java
  src/main/java/com/est/jobshin/domain/interviewDetail/dto/InterviewAnswer.java
  src/main/java/com/est/jobshin/domain/interviewDetail/dto/InterviewDetailDto.java
  src/main/java/com/est/jobshin/domain/interviewDetail/dto/InterviewQuestion.java
  src/main/java/com/est/jobshin/domain/interviewDetail/service/InterviewDetailService.java
  src/main/java/com/est/jobshin/infra/alan/AlanService.java
  src/main/java/com/est/jobshin/infra/alan/PromptMessage.java
  src/main/resources/application.yml
Labels: 버그

#36 Refactor: Refactor: 메세지 프롬프트 및 AlanService 리펙토링
  src/main/java/com/est/jobshin/infra/alan/AlanService.java
  src/main/java/com/est/jobshin/infra/alan/PromptMessage.java
Labels: 리펙토링

#39 Feat: 질문 받아와서 db에 저장, 클라이언트에게 질문 하나씩 전송
  src/main/java/com/est/jobshin/domain/interview/controller/InterviewController.java
  src/main/java/com/est/jobshin/domain/interview/domain/Interview.java
  src/main/java/com/est/jobshin/domain/interview/dto/InterviewDto.java
  src/main/java/com/est/jobshin/domain/interview/dto/QuestionMessage.java
  src/main/java/com/est/jobshin/domain/interview/service/InterviewService.java
  src/main/java/com/est/jobshin/domain/interview/service/MessageQueueService.java
  src/main/java/com/est/jobshin/domain/interviewDetail/controller/InterviewDetailController.java
  src/main/java/com/est/jobshin/domain/interviewDetail/domain/InterviewDetail.java
  src/main/java/com/est/jobshin/domain/interviewDetail/dto/InterviewDetailDto2.java
  src/main/java/com/est/jobshin/domain/interviewDetail/dto/InterviewQuestion.java
  src/main/java/com/est/jobshin/domain/interviewDetail/service/InterviewDetailService.java
  src/main/java/com/est/jobshin/infra/alan/PromptMessage.java
Labels: 기능개발, 리펙토링

#48 Interview2
  src/main/java/com/est/jobshin/domain/interview/controller/InterviewController.java
  src/main/java/com/est/jobshin/domain/interview/domain/Interview.java
  src/main/java/com/est/jobshin/domain/interview/service/InterviewResultService.java
  src/main/java/com/est/jobshin/domain/interviewDetail/domain/InterviewDetail.java
  src/main/java/com/est/jobshin/domain/interviewDetail/dto/InterviewAnswer.java
  src/main/java/com/est/jobshin/domain/interviewDetail/repository/InterviewDetailRepository.java
  src/main/java/com/est/jobshin/domain/interviewDetail/service/InterviewDetailService.java
  src/main/java/com/est/jobshin/domain/levelfeedback/domain/LevelFeedback.java
  src/main/java/com/est/jobshin/domain/levelfeedback/dto/LevelFeedbackDto.java
  src/main/java/com/est/jobshin/infra/alan/AlanService.java
  src/main/java/com/est/jobshin/infra/alan/PromptMessage.java
Labels: 기능개발, 리펙토링

#50 Design: 로그인, 메인 페이지 화면 수정 및 로고 이미지 추가
  src/main/resources/static/css/header.css
  src/main/resources/static/css/main.css
  src/main/resources/static/css/user.css
  src/main/resources/static/img/logo.png
  src/main/resources/templates/layout/header.html
  src/main/resources/templates/layout/main.html
  src/main/resources/templates/user/login.html
Labels: 디자인(화면 설계)

#52 Refactor: 메서드 위치 변경
  src/main/java/com/est/jobshin/domain/interview/controller/InterviewController.java
  src/main/java/com/est/jobshin/domain/interview/domain/Interview.java
  src/main/java/com/est/jobshin/domain/interview/service/InterviewResultService.java
  src/main/java/com/est/jobshin/domain/interviewDetail/service/InterviewDetailService.java
  src/main/java/com/est/jobshin/infra/alan/AlanService.java
  src/main/java/com/est/jobshin/infra/alan/PromptMessage.java
Labels: 리펙토링

#60 Feat: Interview와 User 테이블 연결
  src/main/java/com/est/jobshin/domain/interview/controller/InterviewController.java
  src/main/java/com/est/jobshin/domain/interview/domain/Interview.java
  src/main/java/com/est/jobshin/domain/interview/service/InterviewService.java
  src/main/java/com/est/jobshin/domain/interviewDetail/service/InterviewDetailService.java
  src/main/java/com/est/jobshin/infra/alan/AlanService.java
Labels: 기능개발

#61 Feat: 면접 페이지 생성 및 질문 데이터 뷰 연동
  src/main/java/com/est/jobshin/domain/interview/controller/InterviewController.java
  src/main/java/com/est/jobshin/infra/alan/PromptMessage.java
  src/main/resources/static/css/interviewMainPage.css
  src/main/resources/static/css/interviewPracticeEnter.css
  src/main/resources/static/css/interviewQuestion.css
  src/main/resources/static/css/interviewRealEnter.css
  src/main/resources/static/img/Send.png
  src/main/resources/templates/error.html
  src/main/resources/templates/interview/interviewMainPage.html
  src/main/resources/templates/interview/interviewPracticeEnter.html
  src/main/resources/templates/interview/interviewQuestion.html
  src/main/resources/templates/interview/interviewRealEnter.html
  src/main/resources/templates/layout/main.html
Labels: 기능개발, 디자인(화면 설계)

#64 Style: 코드 최신화용 pr
  src/main/java/com/est/jobshin/domain/interview/controller/InterviewController.java
  src/main/java/com/est/jobshin/domain/interview/controller/ThymeleafController.java
  src/main/resources/static/css/interviewPracticeEnter.css
  src/main/resources/static/css/interviewRealEnter.css
  src/main/resources/templates/interview/interviewMainPage.html
  src/main/resources/templates/interview/interviewPracticeEnter.html
  src/main/resources/templates/interview/interviewQuestion.html
  src/main/resources/templates/interview/interviewRealEnter.html
  src/main/resources/templates/layout/main.html
Labels: 리펙토링, 디자인(화면 설계)
