Repository six-do-string/jobshin, pull requests merged in 2024-09, with the labels that each got.

#72 Feat yunjunho
  src/main/java/com/est/jobshin/domain/interview/controller/InterviewController.java
  src/main/java/com/est/jobshin/domain/interview/domain/Interview.java
  src/main/java/com/est/jobshin/domain/interview/service/InterviewService.java
  src/main/java/com/est/jobshin/domain/interviewDetail/dto/InterviewResultDetail.java
  src/main/java/com/est/jobshin/domain/interviewDetail/service/InterviewDetailService.java
  src/main/java/com/est/jobshin/infra/alan/AlanService.java
  src/main/java/com/est/jobshin/infra/alan/PromptMessage.java
Labels: 기능개발

#74 Refactor: interviewQuestion의 js 코드 수정
  src/main/java/com/est/jobshin/domain/interview/controller/InterviewThymeleafController.java
  src/main/java/com/est/jobshin/domain/interviewDetail/service/InterviewDetailService.java
  src/main/java/com/est/jobshin/infra/alan/AlanService.java
  src/main/resources/templates/AlFeedback.html
  src/main/resources/templates/interview/interviewQuestion.html
  src/main/resources/templates/interview/interviewRealEnter.html
Labels: 리펙토링

#77 Refactor: interviewQuestion 내부 js코드 수정 + 연습모드 질문 데이터 뷰 연동
  src/main/java/com/est/jobshin/domain/interview/controller/InterviewThymeleafController.java
  src/main/resources/templates/AlFeedback.html
  src/main/resources/templates/interview/interviewPracticeEnter.html
  src/main/resources/templates/interview/interviewQuestion.html
  src/main/resources/templates/interview/interviewRealEnter.html
Labels: 리펙토링

#80 Feat: 테스트코드 - UserRepositoryTest
  src/test/java/com/est/jobshin/repository/UserRepositoryTest.java
Labels: 기능개발

#81 Feat: 모의면접 리스트, 상세페이지 기능 및 임시 화면 구현
  src/main/java/com/est/jobshin/domain/interview/domain/Interview.java
  src/main/java/com/est/jobshin/domain/interview/dto/PracticeInterviewHistorySummaryResponse.java
  src/main/java/com/est/jobshin/domain/interview/repository/InterviewRepository.java
  src/main/java/com/est/jobshin/domain/interviewDetail/dto/InterviewDetailsResponse.java
  src/main/java/com/est/jobshin/domain/user/controller/UserController.java
  src/main/java/com/est/jobshin/domain/user/service/UserService.java
  src/main/resources/templates/user/practice_interview_detail.html
  src/main/resources/templates/user/practice_interview_list.html
Labels: 기능개발

#89 Refactor: InterviewQuestion js 코드 수정
  src/main/java/com/est/jobshin/domain/interview/controller/InterviewController.java
  src/main/java/com/est/jobshin/domain/interview/controller/InterviewThymeleafController.java
  src/main/resources/static/css/AlFeedback.css
  src/main/resources/static/css/interviewMainPage.css
  src/main/resources/static/css/interviewPracticeEnter.css
  src/main/resources/static/css/interviewRealEnter.css
  src/main/resources/static/js/LevelFeedback.js
  src/main/resources/templates/AlFeedback.html
  src/main/resources/templates/interview/interviewMainPage.html
  src/main/resources/templates/interview/interviewPracticeEnter.html
  src/main/resources/templates/interview/interviewQuestion.html
  src/main/resources/templates/interview/interviewRealEnter.html
  src/main/resources/templates/levelFeedback.html
Labels: 리펙토링

#91 Test: 테스트코드 - InterviewRepositoryTest 작성
  src/test/java/com/est/jobshin/repository/InterviewRepositoryTest.java
  src/test/java/com/est/jobshin/repository/UserRepositoryTest.java
Labels: test

#93 Test: 테스트코드 - UserServiceTest 수정
  src/test/java/com/est/jobshin/service/UserServiceTest.java
Labels: test

#95 Dev interview2
  src/main/java/com/est/jobshin/domain/interview/controller/InterviewController.java
  src/main/java/com/est/jobshin/domain/interview/controller/InterviewThymeleafController.java
  src/main/java/com/est/jobshin/domain/interview/service/InterviewService.java
  src/main/java/com/est/jobshin/domain/interviewDetail/domain/InterviewDetail.java
  src/main/java/com/est/jobshin/domain/interviewDetail/dto/InterviewResultDetail.java
  src/main/java/com/est/jobshin/domain/interviewDetail/service/InterviewDetailService.java
  src/main/java/com/est/jobshin/infra/alan/PromptMessage.java
  src/main/resources/static/css/interviewMainPage.css
  src/main/resources/static/css/interviewPracticeEnter.css
  src/main/resources/static/css/interviewRealEnter.css
  src/main/resources/static/js/LevelFeedback.js
  src/main/resources/templates/AlFeedback.html
  src/main/resources/templates/interview/interviewMainPage.html
  src/main/resources/templates/interview/interviewPracticeEnter.html
  src/main/resources/templates/interview/interviewQuestion.html
  src/main/resources/templates/interview/interviewRealEnter.html
  src/main/resources/templates/layout/main.html
  src/main/resources/templates/levelFeedback.html
Labels: 기능개발, 리펙토링

#98 Test: 테스트코드 - UserServiceTest 추가 코드 작성중
  src/test/java/com/est/jobshin/repository/InterviewRepositoryTest.java
  src/test/java/com/est/jobshin/repository/UserRepositoryTest.java
  src/test/java/com/est/jobshin/service/UserServiceTest.java
Labels: test

#100 Feat: 사용자 대상 난이도 조사 프론트 부분 구현
  src/main/java/com/est/jobshin/domain/levelfeedback/controller/LevelFeedbackController.java
  src/main/resources/static/css/LevelFeedback.css
  src/main/resources/static/js/LevelFeedback.js
  src/main/resources/templates/AlFeedback.html
  src/main/resources/templates/interview/interviewQuestion.html
  src/main/resources/templates/levelFeedback.html
Labels: 기능개발, 디자인(화면 설계)

#105 fix: score가 null일 때 해당 점수를 제외한 평균값 계산 후 0으로 반환
  src/main/java/com/est/jobshin/domain/user/dto/MyPageInterviewDetailDto.java
Labels: 버그

#108 Yunjunho
  src/main/java/com/est/jobshin/domain/interview/controller/InterviewController.java
  src/main/java/com/est/jobshin/domain/interview/domain/Interview.java
  src/main/java/com/est/jobshin/domain/interview/service/InterviewService.java
  src/main/java/com/est/jobshin/domain/interviewDetail/domain/InterviewDetail.java
  src/main/java/com/est/jobshin/domain/interviewDetail/dto/InterviewQuestion.java
  src/main/resources/static/css/interviewPracticeEnter.css
  src/main/resources/static/css/interviewQuestion.css
  src/main/resources/static/css/interviewRealEnter.css
  src/main/resources/templates/interview/interviewPracticeEnter.html
  src/main/resources/templates/interview/interviewQuestion.html
  src/main/resources/templates/interview/interviewRealEnter.html
Labels: 기능개발

#110 Refactor: 면접결과와 피드백 페이지 연결, 실전모드 질문 생성 api 연결 메서드(createQuestions()) 수정
  src/main/java/com/est/jobshin/domain/interview/controller/InterviewThymeleafController.java
  src/main/resources/static/css/AlFeedback.css
  src/main/resources/static/css/LevelFeedback.css
  src/main/resources/templates/AlFeedback.html
  src/main/resources/templates/interview/interviewPracticeEnter.html
  src/main/resources/templates/interview/interviewQuestion.html
  src/main/resources/templates/interview/interviewRealEnter.html
  src/main/resources/templates/levelFeedback.html
Labels: 리펙토링

#122 Design: 메인 페이지 화면 설계, Interview 리스트 및 상세 페이지 사이드 바 수정
  src/main/java/com/est/jobshin/HomeController.java
  src/main/java/com/est/jobshin/domain/interview/dto/InterviewDto.java
  src/main/java/com/est/jobshin/domain/user/dto/UserDto.java
  src/main/resources/static/css/main.css
  src/main/resources/static/img/information-background-image.png
  src/main/resources/static/img/interview-feedback-mock.png
  src/main/resources/static/img/main-header-mock-image.png
  src/main/resources/static/img/practice-interview-mock.png
  src/main/resources/static/img/real-interview-mock.png
  src/main/resources/templates/layout/main.html
  src/main/resources/templates/user/practice_interview_detail.html
  src/main/resources/templates/user/practice_interview_list.html
  src/main/resources/templates/user/real_interview_detail.html
  src/main/resources/templates/user/real_interview_list.html
Labels: 리펙토링, 디자인(화면 설계)

#114 Test: 모의면접 Service 부분 테스트코드 작성
  .gitignore
  src/test/java/com/est/jobshin/controller/InterviewControllerTest.java
  src/test/java/com/est/jobshin/service/InterviewDetailServiceTest.java
  src/test/java/com/est/jobshin/service/InterviewServiceTest.java
  src/test/resources/application.yml
Labels: test

#117 Feat: 사용자 레벨 조정 기능 추가
  src/main/java/com/est/jobshin/domain/interview/controller/InterviewController.java
  src/main/java/com/est/jobshin/domain/interview/controller/InterviewThymeleafController.java
  src/main/java/com/est/jobshin/domain/interview/domain/Interview.java
  src/main/java/com/est/jobshin/domain/interview/dto/InterviewLevel.java
  src/main/java/com/est/jobshin/domain/interview/repository/InterviewRepository.java
  src/main/java/com/est/jobshin/domain/interview/service/InterviewService.java
  src/main/java/com/est/jobshin/domain/interviewDetail/domain/InterviewDetail.java
  src/main/java/com/est/jobshin/domain/interviewDetail/repository/InterviewDetailRepository.java
  src/main/java/com/est/jobshin/domain/interviewDetail/service/InterviewDetailService.java
  src/main/java/com/est/jobshin/domain/levelfeedback/controller/LevelFeedbackController.java
  src/main/java/com/est/jobshin/domain/levelfeedback/domain/LevelFeedback.java
  src/main/java/com/est/jobshin/domain/levelfeedback/dto/LevelFeedbackDto.java
  src/main/java/com/est/jobshin/domain/levelfeedback/repository/LevelFeedbackRepository.java
  src/main/java/com/est/jobshin/domain/levelfeedback/service/LevelFeedbackService.java
  src/main/java/com/est/jobshin/domain/user/domain/User.java
  src/main/resources/static/js/AlFeedback.js
  src/main/resources/static/js/LevelFeedback.js
  src/main/resources/templates/interview/interviewQuestion.html
  src/main/resources/templates/levelFeedback.html
Labels: 기능개발, 리펙토링

#124 Test: 테스트코드 - UserControllerTest 수정
  src/test/java/com/est/jobshin/controller/UserControllerTest.java
Labels: test

#125 Test: 테스트코드 - UserControllerTest 수정
  src/test/java/com/est/jobshin/controller/UserControllerTest.java
  src/test/java/com/est/jobshin/repository/InterviewRepositoryTest.java
Labels: test

#126 Test: 테스트코드 - UserControllerTest 수정
  src/test/java/com/est/jobshin/repository/InterviewRepositoryTest.java
Labels: test

#127 Test: 테스트코드 - UserControllerTest 수정
  src/test/java/com/est/jobshin/controller/UserControllerTest.java
  src/test/java/com/est/jobshin/repository/InterviewRepositoryTest.java
Labels: test

#129 Refactor: 유저 레벨 업데이트 메서드 파라미터 타입 수정 (+ Design: 면접 입장 페이지 화면, 면접 페이지 링크 추가, 결과 페이지의 토글 버튼 수정)
  src/main/java/com/est/jobshin/domain/interview/controller/InterviewController.java
  src/main/java/com/est/jobshin/domain/interview/controller/InterviewThymeleafController.java
  src/main/java/com/est/jobshin/domain/interview/dto/InterviewLevel.java
  src/main/java/com/est/jobshin/domain/interview/service/InterviewService.java
  src/main/resources/static/css/AlFeedback.css
  src/main/resources/static/css/interviewPracticeEnter.css
  src/main/resources/static/css/interviewQuestion.css
  src/main/resources/static/css/interviewRealEnter.css
  src/main/resources/static/js/AlFeedback.js
  src/main/resources/static/js/LevelFeedback.js
  src/main/resources/templates/AlFeedback.html
  src/main/resources/templates/interview/interviewQuestion.html
  src/main/resources/templates/levelFeedback.html
Labels: 리펙토링, 디자인(화면 설계)

#130 Refactor: 면접 문제 반환 뷰 url 수정
  src/main/java/com/est/jobshin/domain/interview/controller/InterviewThymeleafController.java
  src/main/resources/static/css/interviewQuestion.css
  src/main/resources/templates/interview/interviewPracticeEnter.html
  src/main/resources/templates/interview/interviewQuestion.html
  src/main/resources/templates/interview/interviewRealEnter.html
Labels: 리펙토링

#133 fix: 회원정보 수정 테스트 시 UserResponse가 null로 반환되는 문제 해결 및 코드 정렬
  src/main/java/com/est/jobshin/domain/user/controller/UserController.java
  src/main/java/com/est/jobshin/domain/user/service/UserService.java
Labels: 버그, 리펙토링

#137 Refactor: 사용자 레벨 업데이트 코드, user 도메인으로 이동 및 수정
  src/main/java/com/est/jobshin/domain/interview/controller/InterviewThymeleafController.java
  src/main/java/com/est/jobshin/domain/interview/repository/InterviewRepository.java
  src/main/java/com/est/jobshin/domain/interview/service/InterviewService.java
  src/main/java/com/est/jobshin/domain/user/controller/UserController.java
  src/main/java/com/est/jobshin/domain/user/service/UserService.java
  src/main/java/com/est/jobshin/infra/alan/AlanService.java
  src/main/resources/templates/AlFeedback.html
  src/main/resources/templates/levelFeedback.html
Labels: 리펙토링

#143 Test: 테스트코드 - SecurityTest 구현
  src/test/java/com/est/jobshin/security/SecurityConfigTest.java
Labels: test

#148 Design: 면접 연습모드, 실전모드 입장화면 수정
  src/main/resources/static/css/interviewPracticeEnter.css
  src/main/resources/static/css/interviewRealEnter.css
  src/main/resources/templates/interview/interviewPracticeEnter.html
  src/main/resources/templates/interview/interviewQuestion.html
  src/main/resources/templates/interview/interviewRealEnter.html
Labels: 디자인(화면 설계)

#152 Yunjunho2
  src/main/java/com/est/jobshin/domain/interviewDetail/domain/InterviewDetail.java
  src/main/java/com/est/jobshin/domain/interviewDetail/repository/InterviewDetailRepository.java
  src/main/java/com/est/jobshin/domain/interviewDetail/service/InterviewDetailService.java
Labels: 리펙토링

#154 Design: 이력 조회 리스트, 헤더, 로그인 및 회원가입 에러 메세지 수정
  src/main/resources/static/css/header.css
  src/main/resources/static/css/table.css
  src/main/resources/templates/user/login.html
  src/main/resources/templates/user/practice_interview_list.html
  src/main/resources/templates/user/real_interview_list.html
  src/main/resources/templates/user/signup.html
Labels: 디자인(화면 설계)

#155 Design: header 로그아웃 버튼 cursor 포인터 추가
  src/main/resources/static/css/header.css
  src/main/resources/templates/layout/header.html
Labels: 디자인(화면 설계)

#157 Design: 필요없는 주석, 및 코드 삭제
  src/main/resources/static/js/AlFeedback.js
  src/main/resources/templates/AlFeedback.html
  src/main/resources/templates/interview/interviewQuestion.html
  src/main/resources/templates/interview/interviewRealEnter.html
Labels: 디자인(화면 설계)

#158 Test: InterviewService 테스트 코드 추가
  src/test/java/com/est/jobshin/service/InterviewDetailServiceTest.java
  src/test/java/com/est/jobshin/service/InterviewServiceTest.java
Labels: test

#161 Feat: 들어오는 답변에 대한 순차적 처리를 위한 작업큐
  src/main/java/com/est/jobshin/domain/interview/service/InterviewService.java
Labels: 기능개발

#167 Test: UserServiceTest 오류 수정
  src/test/java/com/est/jobshin/service/UserServiceTest.java
Labels: test

#173 Yunjunho2
  src/main/java/com/est/jobshin/domain/interview/controller/InterviewThymeleafController.java
  src/main/java/com/est/jobshin/domain/interview/service/InterviewService.java
  src/main/java/com/est/jobshin/domain/interviewDetail/util/Category.java
  src/main/resources/templates/interview/interviewPracticeEnter.html
Labels: 리펙토링

#174 Fix: 연습 모드/실전 모드 이력 페이지네이션 계산 오류
  src/main/java/com/est/jobshin/domain/interview/repository/InterviewRepository.java
  src/main/java/com/est/jobshin/domain/user/service/UserService.java
  src/main/resources/templates/user/practice_interview_list.html
Labels: 버그

#176 Fix: 난이도 선택하지 않아도 요청 처리되는 오류 수정
  src/main/resources/templates/levelFeedback.html
Labels: 버그, 리펙토링

#182 Refactor: 모의면접 문제, 결과 로딩 관련 예외 처리 로직 수정 및 연습모드 화면에서 카테고리 일부 잘리는 거 수정
  src/main/java/com/est/jobshin/domain/interview/controller/InterviewThymeleafController.java
  src/main/resources/static/css/interviewPracticeEnter.css
  src/main/resources/templates/interview/AlFeedback.html
  src/main/resources/templates/interview/interviewPracticeEnter.html
  src/main/resources/templates/interview/interviewQuestion.html
  src/main/resources/templates/interview/interviewRealEnter.html
  src/main/resources/templates/interview/levelFeedback.html
Labels: 리펙토링, 디자인(화면 설계)

#183 Test: 테스트코드 - UserIntegrationTest 테스트 코드
  src/test/java/com/est/jobshin/userIntegration/UserIntegrationTest.java
Labels: test

#185 Refactor: 모의면접 에러 메세지 수정 및 불필요한 console.log() 제거
  src/main/resources/templates/interview/AlFeedback.html
  src/main/resources/templates/interview/interviewPracticeEnter.html
  src/main/resources/templates/interview/interviewQuestion.html
  src/main/resources/templates/interview/interviewRealEnter.html
  src/main/resources/templates/interview/levelFeedback.html
Labels: 리펙토링

#193 Fix: 면접 이어하기시 이미 푼 문제도 포함되는 부분 수정
  src/main/java/com/est/jobshin/domain/interview/service/InterviewService.java
  src/main/java/com/est/jobshin/domain/interviewDetail/domain/InterviewDetail.java
  src/main/resources/application.yml
Labels: 리펙토링

#199 Refactor: 코드 리팩터링
  src/main/java/com/est/jobshin/infra/alan/AlanService.java
  src/main/java/com/est/jobshin/infra/alan/PromptMessage.java
Labels: 리펙토링
